AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for storing CloudFormation templates with versioning enabled
Resources:
  CfnTemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
Outputs:
  TemplateBucketName:
    Value: !Ref CfnTemplatesBucket
    Export:
      Name: TemplateBucketName
